FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar script
COPY src/main_v2_merge.py main.py

# Ejecutar
CMD ["python", "main.py"]
